# vimでシェルを使えるようにする
[[plugins]]
repo= 'Shougo/vimshell.vim'
# vimshellを動かすのに必須らしい
[[plugins]]
repo = 'Shougo/vimproc.vim'

# 特定のファイルタイプで読み込む
[[plugins]]
repo  = 'Quramy/tsuquyomi'
on_ft = ['typescript']

[[plugins]]
repo   = 'Shougo/unite.vim'

# unite.vim を読み込んだら一緒に読み込む
[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

# 特定のコマンドを打ったら読み込む
[[plugins]]
repo      = 'thinca/vim-prettyprint'
on_cmd    = ['PP', 'PrettyPrint']

# 特定のマッピングを使ったら読み込む
# 又、gvim でしか利用しない
[[plugins]]
repo   = 'thinca/vim-fontzoom'
on_cmd = ['Fontzoom']
on_map = ['<Plug>(fontzoom-']
gui    = 1

#html5をハイライト
[[plugins]]
repo = 'othree/html5.vim'

# sass
[[plugins]]
repo = 'AtsushiM/search-parent.vim'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

# CSSのカラーを表示する
[[plugins]]
repo = 'ap/vim-css-color'
